name = "economy"
version = "0.1.0"
defaultTargets = ["Economy"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#8eda17ddee44c50e0599125d97edc229a9bb0244"

[[lean_lib]]
name = "Economy"
